### PR TITLE
fix: sign-payload shouldn't recanonicalize payload

### LINKED ISSUE #475: Payload functionality broken ( invalid character '\n' in string literal)
This is tested with commit 7cddf58, built with go version go1.20.2 darwin/arm64

Steps to reproduce:

```
% tuf init                                                       
Repository initialized
% tuf gen-key --scheme=ecdsa-sha2-nistp256 root     
Enter root keys passphrase: 
Repeat root keys passphrase: 
Generated root ecdsa-sha2-nistp256 key with ID 3919d40168ff00a08fe585a20e9ebeeafbde74c30da09a71e70fb9cb6c59281f
% tuf payload root.json > root.json.payload 
 % tuf sign-payload --role=root root.json.payload > root.json.sigs
ERROR: json: error calling MarshalJSON for type json.RawMessage: invalid character '\n' in string literal
```

### PR DESCRIPTION
**Pull request by znewman01**
- Add new `Repo.SignRaw` which doesn't canonicalize before signing (and just returns Signatures)
- Rename `SignPayload` to `CanonicalizeAndSign` (old name is deprecated; it probably doesn't actually get used so we can rip out next major release.)
- Add `sign.MakeSignatures` which does not canonicalize; refactor `sign.Sign` to use it.
- Modify offline flow to test this property.
- Use `SignRaw` in `tuf sign-payload`.

Please fill in the fields below to submit a pull request.  The more information that is provided, the better.

Fixes #475.

Release Notes:
- (API) `Repo.SignPayload` is deprecated; please use `CanonicalizeAndSign` instead.
- (CLI) Fix `tuf sign-payload` to not re-canonicalize the input.

**Types of changes**:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). **Please ensure that your PR title** is a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) breaking change (with a `!`, as in `feat!: change foo`). 

**Description of the changes being introduced by the pull request**:

**Please verify and check that the pull request fulfills the following requirements**:

- [x] Tests have been added for the bug fix or new feature
- [x] Docs have been added for the bug fix or new feature

### CODE REVIEW

File: sign/sign.go [hunk 1]
```diff
@@ -2,46 +2,65 @@ package sign
...
+//
+// There will be one data.Signature for each of k's IDs, each wih the same
+// signature data.
+func MakeSignatures(canonical []byte, k keys.Signer) ([]data.Signature, error) {
+	sigData, err := k.SignMessage(canonical)
+	if err != nil {
+		return nil, err
+	}
+
 	ids := k.PublicData().IDs()
```
Comment (rdimitrov) [inline sign/sign.go:24]: Ah, maybe we should really fix the confusion that with the given implementation there might be more than one key ID per key

**Review by rdimitrov — APPROVED** [review]
lgtm 👍

**Review by joshuagl — APPROVED** [review]
