### PR TITLE
fix: add-signature to read from stdin

### LINKED ISSUE #529: add-signature to read from stdin
Whilst working on https://github.com/theupdateframework/go-tuf/issues/525#issuecomment-1655807670 I found that I had to write the signature out to file and then read it in again when I called `add-signature`. It would be useful if I could avoid the disk IO and pipe the signature into the `add-signature` call. 

```
# current approach
tuf add-signature --signature targets.json.signature targets.json

# proposed solution
cat targets.json.signature | tuf add-signature targets.json
```

### PR DESCRIPTION
**Pull request by ChevronTango**
Please fill in the fields below to submit a pull request.  The more information that is provided, the better.

Fixes #529 

Release Notes: add-signature to read from stdin

**Types of changes**:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected). **Please ensure that your PR title** is a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) breaking change (with a `!`, as in `feat!: change foo`). 

**Description of the changes being introduced by the pull request**:
add-signature to read from stdin

**Please verify and check that the pull request fulfills the following requirements**:

- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

File: cmd/tuf/add_signatures.go [hunk 1]
```diff
@@ -12,21 +12,34 @@ import (
...
 
-	f := args.String["<sig_file>"]
-	sigBytes, err := os.ReadFile(f)
-	if err != nil {
-		return err
+	f := args.String["--signatures"]
+	var sigBytes []byte
+	var err error
+	if f != "" {
+		sigBytes, err = os.ReadFile(f)
```
Comment (mnm678) [inline cmd/tuf/add_signatures.go:32]: Does this need to read `<sig_file>` instead of `--signatures`?

**Review by mnm678 — COMMENTED** [review]
Thanks for the pr! I have one nit and a question, but overall this looks good.

File: cmd/tuf/add_signatures.go (hunk 1 above)
Comment (ChevronTango) [reply cmd/tuf/add_signatures.go:32]: In testing, because signatures is now optional it gets brought under the `--signatures` key rather than being standalone as it was before.

**Review by mnm678 — DISMISSED** [review]

File: cmd/tuf/add_signatures.go [hunk 2]
```diff
@@ -12,21 +12,34 @@ import (
...
+		if err != nil {
+			return err
+		}
+	} else {
+		var input string
+		_, err := fmt.Scan(&input)
```
Comment (rdimitrov) [inline cmd/tuf/add_signatures.go:38]: [Scan()](https://pkg.go.dev/fmt#Scan) also returns a number of objects being scanned, so it'd be nice to take that into account and make sure you're getting exactly one object/signature.

**Comment by ChevronTango** [comment]
@rdimitrov is there anything more I can do to help get this merged?

**Comment by trishankatdatadog** [comment]
> @rdimitrov is there anything more I can do to help get this merged?

Could we resolve conflicts first pls?

**Comment by ChevronTango** [comment]
> > @rdimitrov is there anything more I can do to help get this merged?
> 
> Could we resolve conflicts first pls?

Thanks @trishankatdatadog that should be merged in now.

**Review by rdimitrov — DISMISSED** [review]

**Comment by trishankatdatadog** [comment]
> Thanks @trishankatdatadog that should be merged in now.

Not sure why yet, but GH claims cannot rebase master into this branch due to conflicts. Would you pls check again?

**Comment by ChevronTango** [comment]
> > Thanks @trishankatdatadog that should be merged in now.
> 
> Not sure why yet, but GH claims cannot rebase master into this branch due to conflicts. Would you pls check again?

no idea why that was still being picky... but should be fine now.

**Review by rdimitrov — APPROVED** [review]

**Review by trishankatdatadog — APPROVED** [review]
