### PR TITLE
fix: verify length and hashes of fetched bytes before parsing

### LINKED ISSUE #233: metadata hashes used in a way that negates security benefits
There seems to be a logic mistake in the way hash checks are done WRT parsing metadata: the point of having hashes for metadata is that parsing completely unverified data can be avoided. The go-tuf client implementation parses the metadata before checking the content hash. This makes using metadata hashes a bit pointless: Once the metadata has been parsed, we have access to signatures...

Details: `downloadMetaFromTimestamp()` downloads bytes, then calls `GenerateTimestampFileMeta()` that parses bytes to metadata. Then it calls `TimestampFileMetaEqual()` to verify byte hashes. I did not look at the same process for snapshot but I assume same is true there.

The logical order for these operations is:
* download bytes 
* check hashes of the bytes
* data is now known to be "vouched for" by delegating metadata: parse/unmarshal bytes into metadata
* do the checks that require parsed metadata (signature, version, etc, ...)

this order is documented in the spec as well, although it does not explain the reason for this order of events and does not specify that data should not be parsed before hash checks.

see also #229

### PR DESCRIPTION
**Pull request by joshuagl**
Fixes #233
Release Notes: 
Check hashes and length of downloaded snapshot and targets metadata before parsing.

**Types of changes**:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

**Description of the changes being introduced by the pull request**:
Better match the specification by performing checks against length and hashes on the downloaded bytes before parsing the bytes into a FileMeta.

**Please verify and check that the pull request fulfills the following requirements**:

- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

### CODE REVIEW

File: util/util.go [hunk 1]
```diff
@@ -86,6 +86,33 @@ func FileMetaEqual(actual data.FileMeta, expected data.FileMeta) error {
 	return nil
 }
 
+func BytesMatchLenAndHashes(fetched []byte, length int64, hashes data.Hashes) error {
+	flen := int64(len(fetched))
+	if length != 0 && flen != length {
+		return ErrWrongLength{length, flen}
+	}
+
+	if len(hashes) != 0 {
```
Comment (mnm678) [inline util/util.go:95]: Should this error if there are no hashes?

Comment (joshuagl) [reply util/util.go:95]: I don't think so, length and hashes are both optional for [`METAFILES`](https://theupdateframework.github.io/specification/latest/#metafiles).

**Review by mnm678 — DISMISSED** [review]

File: util/util.go (hunk 1 above)
Comment (znewman01) [inline util/util.go:95]: Why do we need the `!= 0` check? (This is probably my Go inexperience showing)

**Review by znewman01 — DISMISSED** [review]

File: util/util.go (hunk 1 above)
Comment (rdimitrov) [reply util/util.go:95]: That's right, the `len` check can be omitted since it will skip the `for` loop if there are no `hashes` entries 👍

**Review by rdimitrov — CHANGES_REQUESTED** [review]
I'd suggest we add a few simple unit tests for `BytesMatchLenAndHashes` and `VersionEqual` in `util_tests.go`, so we know in case they break at some point 👍 Other than that, it's great 👍 🙏

File: util/util.go (hunk 1 above)
Comment (joshuagl) [reply util/util.go]: Well spotted both, thanks! This was my Go inexperience showing :-) Removed the `len()` check in [39b9b0f](https://github.com/theupdateframework/go-tuf/pull/325/commits/39b9b0f1c495d2be5ff14317f0248dce5327e05d)

**Comment by joshuagl** [comment]
I've add some tests in af46f5d and removed the unnecessary `len()` check in 39b9b0f. I've also rebased on the latest master branch and force pushed.

PTAL @mnm678 @znewman01  @rdimitrov 🙏

**Review by rdimitrov — APPROVED** [review]
Thanks! 👍 LGTM! 💯

**Review by znewman01 — APPROVED** [review]
